export default {
	steps:'Steps',
	note:'Note',
	general:{
		item:'General',
		title:'Guide general',
		description:'In this guide you will find an overview of the main functionalities of the system, which can be accessed generally from the side menu.',
		description_performance:'In this section of the system you can see all the operations that the system has performed on your behalf. The view will show you the number of operations carried out, the percentage of success, the total value of the returns obtained and a table with detailed information on each operation. Use the "demo" option to see results of the operations that did not affect your real account and / or change the filters to obtain the desired results.',
		description_commission:'This view allows you to view all the commissions generated to date with the licenses that you have active. This section also allows you to view and pay the commissions that were generated by licenses that have already expired.',
		description_service:'Use this section to see and configure the services that the system has available to you, this view shows you detailed information about each service and also allows you to make the purchase of the license that you want.',
		description_license:'In this section of the system you can find all the licenses you have purchased, here you can view important information about each license (purchase date, activation date, expiration date ... etc). This section should also be used to activate your licenses after the purchase has been processed.',
		description_setting:'In the configuration section you can perform tasks such as changing your system access password and registering your broker account.',
	},
	buy_license:{
		item:'Buy licenses',
		title:'License buying guide',

		description:'To purchase the license for a service, follow the steps listed in this guide. To ensure that your payment is successful, follow the steps to the letter.',
		step_1:'Go to the services section.',
		step_2:'In "Services and licenses" locate the service that interests you and click the "Show licenses" button.',
		step_3:'Identify the license you wish to purchase and click on the license purchase button (the value of the commissions pending payment, if any, will be added).',
		step_4:'Select the payment option and fill in the necessary information.',
		step_5:'Finish the payment according to the selected option.',
		step_6:'Check your purchase in the licenses section.'
	},
	active_license:{
		item:'Activate licenses',
		title:'License activation guide',

		description:'To activate your licenses, follow the steps listed in this guide.',
		note:'The system allows you to have a single active license per service, if you have more than one license for the same service, you must wait for the active license to expire before you can activate another one. The associated free and indefinite use licenses will always remain active, the system will use its paid licenses if they exist, otherwise the free licenses will be used.',
		step_1:'Go to the licenses section.',
		step_2:'Identify the license you want to activate.',
		step_3:'Click on the license activation button.',
		step_4:'Confirm license activation.',
	},
	check_pay_commission:{
		item:'Check and pay commissions',
		title:'Consultation guide and commission payment',

		description:'To check and pay your commissions, follow the steps listed in this guide. To ensure that your payment is made correctly follow the steps to the letter.',
		note:'Commissions are automatically generated when the profits reach or exceed the license commission level or when the license expiration date has been reached (the commission value depends on the performance achieved and the license that is active), Once a commission is generated, the commission payment must be made to continue using TrSoft products.',
		step_1:'Go to the commissions section.',
		step_2:'The system will show you the commissions that have been generated and the commissions calculated so far for the licenses you have active.',
		step_3:'Identify the commission you want to pay.',
		step_4:'Click on one of the payment options available in the commission.',
		step_5:'Fill in the necessary information',
		step_6:'Finish the payment according to the selected payment option.',
		another_way_to_pay:'Another way to pay',
		another_way_to_pay_msg:'If you plan to purchase a license after paying the commissions, you can go directly to purchasing the license and the value of the commissions pending payment will be added to the purchase value of your license.',
	},
	start_copy_binary:{
		item:'Start Copy Binary',
		title:'Start guide with Copy Binary',
		description:'Copy Binary allows you to execute trades based on the decisions of our traders. To use this service be sure to meet the following requirements.',
		req_1:'Have an active license for the service (free licenses apply)',
		req_2:'Have an active account at the <1> IqOption </1> broker.',
		req_3:'Have a balance available in your IqOption account, depending on how you want to operate (real or practice account).',

		steps_text:'If you meet all the requirements listed above, follow the steps listed below to configure and start TrSoft - Copy Binary:',

		step_1:'Configure access to IqOption, in the settings section you can register your access to the IqOption platform. This is necessary so that the operations carried out by our traders can be copied to your account.',
		step_2:'Configure the options as you wish (Take into account the recommendations made by TrSoft).',
	}
}