export default {
    SET_CONFIG:'SET_CONFIG',
    SET_HEADERS:'SET_HEADERS',
    LOAD_SEARCH:'LOAD_SEARCH',
    NO_LOAD_SEARCH:'NO_LOAD_SEARCH',
    LOAD_TABLE:'LOAD_TABLE',
    NO_LOAD_TABLE:'NO_LOAD_TABLE',
}
